In [ ]:
!pip install tensorflow

In [24]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

#### Base de dados de frutas
0 - Maçã<br>
1 - Limão<br>
2 - Melão 

In [25]:
# importando dataset
dataset = pd.read_csv("frutas.csv")
dataset.head()

ph  peso(kg)  diametro(cm)  fruta
0  2.980056  0.059878      8.303492      0
1  2.619839  0.059534      9.563558      0
2  2.983526  0.040029      8.921555      0
3  2.827375  0.046539      5.919455      0
4  2.979685  0.055912      9.392527      0

In [26]:
# extraindo características (x)
x = np.array(dataset.loc[:, ["ph", "peso(kg)", "diametro(cm)"]])

# extraindo resultado
d = np.array(dataset.loc[:,"fruta"])

# Embaralhando os dados
shuffle = np.random.permutation(len(x))
x = x[shuffle]
d = d[shuffle]

# Separando dados de treino (20%) e teste (20%)
limite = int(len(x) * 0.8)

x_treino = x[0:limite]
x_teste = x[limite: ]

d_treino = d[0:limite]
d_teste = d[limite: ]

### Criando modelo do keras

**Sequential** : Modelo sequencial, onde cada camada possui um vetor de entradas e um vetor de saídas<br>
**Flatten** : Camada de entrada, redimensiona os dados (caso a entrada seja uma matriz, por exemplo)<br>
**Dense** : Camada regular

Referências: https://www.tensorflow.org/tutorials/keras/classification?hl=pt-br , https://keras.io/about/

In [27]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, 3)),
    keras.layers.Dense(8, activation='sigmoid'),
    keras.layers.Dense(5, activation='sigmoid'),
    keras.layers.Dense(3, activation='softmax')
])

In [28]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
model.fit(x_treino, d_treino, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1339 - accuracy: 0.3611
Epoch 2/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.1296 - accuracy: 0.3611
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1264 - accuracy: 0.3611
Epoch 4/1000
3/3 [==============================] - 0s 6ms/step - loss: 1.1226 - accuracy: 0.3611
Epoch 5/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1194 - accuracy: 0.3611
Epoch 6/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.1163 - accuracy: 0.3611
Epoch 7/1000
3/3 [==============================] - ETA: 0s - loss: 1.0703 - accuracy: 0.43 - 0s 10ms/step - loss: 1.1126 - accuracy: 0.3611
Epoch 8/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.1100 - accuracy: 0.3611
Epoch 9/1000
3/3 [==============================] - 0s 6ms/step - loss: 1.1068 - accuracy: 0.3611
Epoch 10/1000
3/3 [==============================] - 0s 12ms/step - loss: 1

3/3 [==============================] - 0s 4ms/step - loss: 1.0085 - accuracy: 0.6667
Epoch 79/1000
3/3 [==============================] - ETA: 0s - loss: 0.9979 - accuracy: 0.68 - 0s 5ms/step - loss: 1.0072 - accuracy: 0.6667
Epoch 80/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0060 - accuracy: 0.6667
Epoch 81/1000
3/3 [==============================] - 0s 5ms/step - loss: 1.0046 - accuracy: 0.6667
Epoch 82/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0037 - accuracy: 0.6667
Epoch 83/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0025 - accuracy: 0.6667
Epoch 84/1000
3/3 [==============================] - ETA: 0s - loss: 1.0090 - accuracy: 0.65 - 0s 4ms/step - loss: 1.0014 - accuracy: 0.6667
Epoch 85/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0002 - accuracy: 0.6667
Epoch 86/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9990 - accuracy: 0.6667
Epoch 87/1000
3/3 [====================

3/3 [==============================] - 0s 3ms/step - loss: 0.8826 - accuracy: 0.8194
Epoch 159/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.8807 - accuracy: 0.7917
Epoch 160/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.8789 - accuracy: 0.7639
Epoch 161/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.8769 - accuracy: 0.7639
Epoch 162/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8751 - accuracy: 0.7639
Epoch 163/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.8731 - accuracy: 0.7639
Epoch 164/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8713 - accuracy: 0.7639
Epoch 165/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.8693 - accuracy: 0.7639
Epoch 166/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.8672 - accuracy: 0.7639
Epoch 167/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.8652 - accuracy: 0.7917
Epoch 168/1000


Epoch 240/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7104 - accuracy: 0.8472
Epoch 241/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.7085 - accuracy: 0.8333
Epoch 242/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7065 - accuracy: 0.8194
Epoch 243/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7045 - accuracy: 0.7917
Epoch 244/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.7025 - accuracy: 0.7917
Epoch 245/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7006 - accuracy: 0.7917
Epoch 246/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6987 - accuracy: 0.7917
Epoch 247/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6967 - accuracy: 0.7917
Epoch 248/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.6948 - accuracy: 0.7917
Epoch 249/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.6927 - accuracy: 0.7917


3/3 [==============================] - 0s 3ms/step - loss: 0.5762 - accuracy: 0.8750
Epoch 322/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.5748 - accuracy: 0.8750
Epoch 323/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5737 - accuracy: 0.8750
Epoch 324/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5725 - accuracy: 0.8750
Epoch 325/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5713 - accuracy: 0.8750
Epoch 326/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5700 - accuracy: 0.8750
Epoch 327/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5687 - accuracy: 0.8750
Epoch 328/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5674 - accuracy: 0.8750
Epoch 329/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5662 - accuracy: 0.8750
Epoch 330/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5649 - accuracy: 0.8750
Epoch 331/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.4949 - accuracy: 0.8889
Epoch 403/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4941 - accuracy: 0.8889
Epoch 404/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.4932 - accuracy: 0.8889
Epoch 405/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4925 - accuracy: 0.8889
Epoch 406/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4916 - accuracy: 0.8889
Epoch 407/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4907 - accuracy: 0.8889
Epoch 408/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4898 - accuracy: 0.9028
Epoch 409/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4892 - accuracy: 0.9028
Epoch 410/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4885 - accuracy: 0.9167
Epoch 411/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4875 - accuracy: 0.9167
Epoch 412/1000


3/3 [==============================] - 0s 1ms/step - loss: 0.4383 - accuracy: 0.9306
Epoch 484/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4381 - accuracy: 0.9306
Epoch 485/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.9306
Epoch 486/1000
3/3 [==============================] - ETA: 0s - loss: 0.4742 - accuracy: 0.90 - 0s 3ms/step - loss: 0.4368 - accuracy: 0.9306
Epoch 487/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4359 - accuracy: 0.9306
Epoch 488/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4354 - accuracy: 0.9306
Epoch 489/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4348 - accuracy: 0.9306
Epoch 490/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4343 - accuracy: 0.9306
Epoch 491/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4337 - accuracy: 0.9306
Epoch 492/1000
3/3 [==============================] - 0s 3ms/step - loss:

3/3 [==============================] - 0s 2ms/step - loss: 0.3912 - accuracy: 0.9306
Epoch 565/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.3906 - accuracy: 0.9306
Epoch 566/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3900 - accuracy: 0.9306
Epoch 567/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3894 - accuracy: 0.9306
Epoch 568/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3889 - accuracy: 0.9306
Epoch 569/1000
3/3 [==============================] - 0s 7ms/step - loss: 0.3881 - accuracy: 0.9306
Epoch 570/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3876 - accuracy: 0.9306
Epoch 571/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3865 - accuracy: 0.9306
Epoch 572/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3857 - accuracy: 0.9444
Epoch 573/1000
3/3 [==============================] - 0s 9ms/step - loss: 0.3858 - accuracy: 0.9444
Epoch 574/1000


3/3 [==============================] - 0s 1ms/step - loss: 0.3438 - accuracy: 0.9444
Epoch 646/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3432 - accuracy: 0.9444
Epoch 647/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.9444
Epoch 648/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.9444
Epoch 649/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3414 - accuracy: 0.9444
Epoch 650/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3410 - accuracy: 0.9444
Epoch 651/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.9444
Epoch 652/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.3396 - accuracy: 0.9444
Epoch 653/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3391 - accuracy: 0.9583
Epoch 654/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.9583
Epoch 655/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.2962 - accuracy: 0.9583
Epoch 728/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2956 - accuracy: 0.9583
Epoch 729/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2951 - accuracy: 0.9583
Epoch 730/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2945 - accuracy: 0.9583
Epoch 731/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2940 - accuracy: 0.9583
Epoch 732/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2936 - accuracy: 0.9583
Epoch 733/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2931 - accuracy: 0.9583
Epoch 734/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2925 - accuracy: 0.9583
Epoch 735/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2919 - accuracy: 0.9583
Epoch 736/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.2911 - accuracy: 0.9583
Epoch 737/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.2518 - accuracy: 0.9583
Epoch 808/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2512 - accuracy: 0.9583
Epoch 809/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2508 - accuracy: 0.9583
Epoch 810/1000
3/3 [==============================] - 0s 8ms/step - loss: 0.2503 - accuracy: 0.9583
Epoch 811/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2496 - accuracy: 0.9583
Epoch 812/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2493 - accuracy: 0.9583
Epoch 813/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2487 - accuracy: 0.9583
Epoch 814/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2486 - accuracy: 0.9583
Epoch 815/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2478 - accuracy: 0.9583
Epoch 816/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.2471 - accuracy: 0.9583
Epoch 817/1000


3/3 [==============================] - 0s 5ms/step - loss: 0.2115 - accuracy: 0.9722
Epoch 889/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2110 - accuracy: 0.9722
Epoch 890/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2107 - accuracy: 0.9722
Epoch 891/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2102 - accuracy: 0.9583
Epoch 892/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2098 - accuracy: 0.9722
Epoch 893/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2093 - accuracy: 0.9722
Epoch 894/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2089 - accuracy: 0.9722
Epoch 895/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.2083 - accuracy: 0.9722
Epoch 896/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2079 - accuracy: 0.9722
Epoch 897/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2077 - accuracy: 0.9722
Epoch 898/1000


Epoch 968/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1775 - accuracy: 0.9861
Epoch 969/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1769 - accuracy: 0.9861
Epoch 970/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1764 - accuracy: 0.9861
Epoch 971/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1762 - accuracy: 0.9861
Epoch 972/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1756 - accuracy: 0.9861
Epoch 973/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1756 - accuracy: 1.0000
Epoch 974/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.1758 - accuracy: 1.0000
Epoch 975/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1755 - accuracy: 1.0000
Epoch 976/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1751 - accuracy: 1.0000
Epoch 977/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1748 - accuracy: 1.0000


In [30]:
previsao = model.predict(x_teste)
print(previsao)

[[2.3549676e-01 7.6190001e-01 2.6032287e-03]
 [8.5334057e-01 1.0350355e-01 4.3155853e-02]
 [6.8339473e-01 3.0223429e-01 1.4371036e-02]
 [2.4686120e-01 7.5045514e-01 2.6836374e-03]
 [5.9864592e-02 5.0486275e-04 9.3963051e-01]
 [1.7932405e-01 8.1904602e-01 1.6300073e-03]
 [7.0042819e-02 6.0273899e-04 9.2935449e-01]
 [5.4505840e-02 4.5006908e-04 9.4504404e-01]
 [8.8262200e-01 5.7990182e-02 5.9387773e-02]
 [1.1223172e-01 8.8691390e-01 8.5435685e-04]
 [4.2873940e-01 5.6544244e-01 5.8181966e-03]
 [7.7934790e-01 2.6292125e-02 1.9435988e-01]
 [1.6411458e-01 8.3448195e-01 1.4034476e-03]
 [2.3825747e-01 7.5912368e-01 2.6189415e-03]
 [7.8689200e-01 1.9192237e-01 2.1185666e-02]
 [6.2309023e-02 5.3104758e-04 9.3715996e-01]
 [1.9929528e-01 7.9873127e-01 1.9734034e-03]
 [1.0824399e-01 8.9093697e-01 8.1903290e-04]]


In [31]:
# Mapeando vetor para classe
def classificar(vetor):
    classes = []
    for y in vetor:
        maximo = np.argmax(y)
        classes.append(maximo)
        
    return classes

In [32]:
classificar(previsao)

[1, 0, 0, 1, 2, 1, 2, 2, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1]

In [33]:
d_teste

array([1, 0, 0, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1], dtype=int64)

#### Comparando modelos

In [34]:
modelo1 = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, 3)),
    keras.layers.Dense(8, activation='sigmoid'),
    keras.layers.Dense(5, activation='sigmoid'),
    keras.layers.Dense(3, activation='softmax')
])

modelo2 = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, 3)),
    keras.layers.Dense(5, activation='sigmoid'),
    keras.layers.Dense(4, activation='sigmoid'),
    keras.layers.Dense(3, activation='softmax')
])

modelo3 = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, 3)),
    keras.layers.Dense(24, activation='sigmoid'),
    keras.layers.Dense(12, activation='sigmoid'),
    keras.layers.Dense(6, activation='sigmoid'),
    keras.layers.Dense(3, activation='softmax')
])

modelo1.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelo2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelo3.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [35]:
modelo1.fit(x_treino, d_treino, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 0s 1ms/step - loss: 1.0991 - accuracy: 0.3611
Epoch 2/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0975 - accuracy: 0.3611
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0966 - accuracy: 0.3611
Epoch 4/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0956 - accuracy: 0.3611
Epoch 5/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0947 - accuracy: 0.3611
Epoch 6/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0941 - accuracy: 0.3611
Epoch 7/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0937 - accuracy: 0.3611
Epoch 8/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0929 - accuracy: 0.3611
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0924 - accuracy: 0.3611
Epoch 10/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0918 - accuracy: 0.3611
Epoch 11/1000
3/3 [

3/3 [==============================] - 0s 3ms/step - loss: 1.0634 - accuracy: 0.3889
Epoch 79/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0627 - accuracy: 0.4028
Epoch 80/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0619 - accuracy: 0.3889
Epoch 81/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0612 - accuracy: 0.3889
Epoch 82/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0604 - accuracy: 0.3611
Epoch 83/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0597 - accuracy: 0.3611
Epoch 84/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0588 - accuracy: 0.3611
Epoch 85/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0580 - accuracy: 0.3889
Epoch 86/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0572 - accuracy: 0.3889
Epoch 87/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0563 - accuracy: 0.4028
Epoch 88/1000
3/3 [=====

3/3 [==============================] - 0s 2ms/step - loss: 0.9492 - accuracy: 0.6806
Epoch 160/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9467 - accuracy: 0.6806
Epoch 161/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9443 - accuracy: 0.6806
Epoch 162/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9418 - accuracy: 0.6806
Epoch 163/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9394 - accuracy: 0.6806
Epoch 164/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.9368 - accuracy: 0.6806
Epoch 165/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.9345 - accuracy: 0.6806
Epoch 166/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9318 - accuracy: 0.6806
Epoch 167/1000
3/3 [==============================] - 0s 998us/step - loss: 0.9294 - accuracy: 0.6806
Epoch 168/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9269 - accuracy: 0.6806
Epoch 169/100

3/3 [==============================] - 0s 2ms/step - loss: 0.7241 - accuracy: 0.6944
Epoch 241/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7216 - accuracy: 0.6944
Epoch 242/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7190 - accuracy: 0.6944
Epoch 243/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7164 - accuracy: 0.6944
Epoch 244/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7138 - accuracy: 0.6944
Epoch 245/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7114 - accuracy: 0.6944
Epoch 246/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7089 - accuracy: 0.6944
Epoch 247/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7066 - accuracy: 0.6944
Epoch 248/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7043 - accuracy: 0.6944
Epoch 249/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7019 - accuracy: 0.6944
Epoch 250/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.5808 - accuracy: 0.6944
Epoch 322/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5797 - accuracy: 0.6944
Epoch 323/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5786 - accuracy: 0.6944
Epoch 324/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5775 - accuracy: 0.6944
Epoch 325/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5764 - accuracy: 0.6944
Epoch 326/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5753 - accuracy: 0.6944
Epoch 327/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5743 - accuracy: 0.6944
Epoch 328/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5733 - accuracy: 0.6944
Epoch 329/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5723 - accuracy: 0.6944
Epoch 330/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5712 - accuracy: 0.6944
Epoch 331/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.5188 - accuracy: 0.6944
Epoch 402/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5183 - accuracy: 0.6944
Epoch 403/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5177 - accuracy: 0.6944
Epoch 404/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5172 - accuracy: 0.6944
Epoch 405/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5167 - accuracy: 0.6944
Epoch 406/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5162 - accuracy: 0.6944
Epoch 407/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5158 - accuracy: 0.6944
Epoch 408/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5153 - accuracy: 0.6944
Epoch 409/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5148 - accuracy: 0.6944
Epoch 410/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5142 - accuracy: 0.6944
Epoch 411/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.4866 - accuracy: 0.6944
Epoch 483/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4863 - accuracy: 0.6944
Epoch 484/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4859 - accuracy: 0.6944
Epoch 485/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4856 - accuracy: 0.6944
Epoch 486/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4853 - accuracy: 0.6944
Epoch 487/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4850 - accuracy: 0.6944
Epoch 488/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4847 - accuracy: 0.6944
Epoch 489/1000
3/3 [==============================] - ETA: 0s - loss: 0.4331 - accuracy: 0.75 - 0s 2ms/step - loss: 0.4844 - accuracy: 0.6944
Epoch 490/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4841 - accuracy: 0.6944
Epoch 491/1000
3/3 [==============================] - 0s 1ms/step - loss:

3/3 [==============================] - 0s 3ms/step - loss: 0.4635 - accuracy: 0.8194
Epoch 564/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4634 - accuracy: 0.8056
Epoch 565/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4632 - accuracy: 0.7917
Epoch 566/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4627 - accuracy: 0.7917
Epoch 567/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4625 - accuracy: 0.8194
Epoch 568/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4621 - accuracy: 0.8194
Epoch 569/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4618 - accuracy: 0.8056
Epoch 570/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4615 - accuracy: 0.8194
Epoch 571/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4613 - accuracy: 0.8056
Epoch 572/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4610 - accuracy: 0.8194
Epoch 573/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.4362 - accuracy: 0.8472
Epoch 645/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4360 - accuracy: 0.8472
Epoch 646/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4355 - accuracy: 0.8472
Epoch 647/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4351 - accuracy: 0.8472
Epoch 648/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4347 - accuracy: 0.8472
Epoch 649/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4344 - accuracy: 0.8611
Epoch 650/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4339 - accuracy: 0.8611
Epoch 651/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4335 - accuracy: 0.8472
Epoch 652/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4329 - accuracy: 0.8472
Epoch 653/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4324 - accuracy: 0.8472
Epoch 654/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.9028
Epoch 726/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3911 - accuracy: 0.9167
Epoch 727/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3904 - accuracy: 0.9167
Epoch 728/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.3897 - accuracy: 0.9167
Epoch 729/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3893 - accuracy: 0.9306
Epoch 730/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3886 - accuracy: 0.9306
Epoch 731/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3881 - accuracy: 0.9306
Epoch 732/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3875 - accuracy: 0.9306
Epoch 733/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3869 - accuracy: 0.9306
Epoch 734/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3861 - accuracy: 0.9306
Epoch 735/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.9583
Epoch 807/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3341 - accuracy: 0.9583
Epoch 808/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.9444
Epoch 809/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3328 - accuracy: 0.9444
Epoch 810/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3321 - accuracy: 0.9444
Epoch 811/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3314 - accuracy: 0.9444
Epoch 812/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.9444
Epoch 813/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3295 - accuracy: 0.9444
Epoch 814/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3288 - accuracy: 0.9444
Epoch 815/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3283 - accuracy: 0.9583
Epoch 816/1000


Epoch 886/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2775 - accuracy: 0.9583
Epoch 887/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.2770 - accuracy: 0.9583
Epoch 888/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2762 - accuracy: 0.9583
Epoch 889/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2754 - accuracy: 0.9583
Epoch 890/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2745 - accuracy: 0.9583
Epoch 891/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2738 - accuracy: 0.9583
Epoch 892/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2731 - accuracy: 0.9583
Epoch 893/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2724 - accuracy: 0.9583
Epoch 894/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2717 - accuracy: 0.9583
Epoch 895/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.2711 - accuracy: 0.9583


3/3 [==============================] - 0s 1ms/step - loss: 0.2263 - accuracy: 0.9583
Epoch 968/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2257 - accuracy: 0.9583
Epoch 969/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2251 - accuracy: 0.9722
Epoch 970/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2246 - accuracy: 0.9861
Epoch 971/1000
3/3 [==============================] - ETA: 0s - loss: 0.2209 - accuracy: 0.96 - 0s 2ms/step - loss: 0.2240 - accuracy: 0.9861
Epoch 972/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2235 - accuracy: 0.9722
Epoch 973/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2229 - accuracy: 0.9722
Epoch 974/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2224 - accuracy: 0.9722
Epoch 975/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2218 - accuracy: 0.9722
Epoch 976/1000
3/3 [==============================] - 0s 2ms/step - loss:

In [36]:
modelo2.fit(x_treino, d_treino, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.2615 - accuracy: 0.3611
Epoch 2/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2561 - accuracy: 0.3611
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2508 - accuracy: 0.3611
Epoch 4/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2461 - accuracy: 0.3611
Epoch 5/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2408 - accuracy: 0.3611
Epoch 6/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.2359 - accuracy: 0.3611
Epoch 7/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2314 - accuracy: 0.3611
Epoch 8/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2267 - accuracy: 0.3611
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2222 - accuracy: 0.3611
Epoch 10/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2183 - accuracy: 0.3611
Epoch 11/1000
3/3 [

3/3 [==============================] - 0s 2ms/step - loss: 1.0773 - accuracy: 0.3611
Epoch 80/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0758 - accuracy: 0.3611
Epoch 81/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0743 - accuracy: 0.3611
Epoch 82/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0728 - accuracy: 0.3611
Epoch 83/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0712 - accuracy: 0.3611
Epoch 84/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0699 - accuracy: 0.3611
Epoch 85/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0682 - accuracy: 0.3611
Epoch 86/1000
3/3 [==============================] - ETA: 0s - loss: 1.0646 - accuracy: 0.37 - 0s 2ms/step - loss: 1.0668 - accuracy: 0.3611
Epoch 87/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.0652 - accuracy: 0.3611
Epoch 88/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.0638 -

Epoch 160/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.9903 - accuracy: 0.6389
Epoch 161/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9891 - accuracy: 0.6528
Epoch 162/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9883 - accuracy: 0.6528
Epoch 163/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.9872 - accuracy: 0.6667
Epoch 164/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9861 - accuracy: 0.6667
Epoch 165/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9850 - accuracy: 0.6667
Epoch 166/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9840 - accuracy: 0.6667
Epoch 167/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9829 - accuracy: 0.6667
Epoch 168/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9819 - accuracy: 0.6667
Epoch 169/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.9806 - accuracy: 0.6667


3/3 [==============================] - 0s 2ms/step - loss: 0.8774 - accuracy: 0.6944
Epoch 242/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8757 - accuracy: 0.7083
Epoch 243/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8740 - accuracy: 0.7083
Epoch 244/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8722 - accuracy: 0.7083
Epoch 245/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8705 - accuracy: 0.7083
Epoch 246/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.8688 - accuracy: 0.7361
Epoch 247/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8670 - accuracy: 0.7361
Epoch 248/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.8655 - accuracy: 0.7222
Epoch 249/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.8638 - accuracy: 0.7083
Epoch 250/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.8621 - accuracy: 0.7083
Epoch 251/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.7308 - accuracy: 0.7083
Epoch 324/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.7291 - accuracy: 0.7083
Epoch 325/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7274 - accuracy: 0.7222
Epoch 326/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7258 - accuracy: 0.7361
Epoch 327/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7243 - accuracy: 0.7361
Epoch 328/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7228 - accuracy: 0.7361
Epoch 329/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7210 - accuracy: 0.7361
Epoch 330/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.7192 - accuracy: 0.7361
Epoch 331/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.7175 - accuracy: 0.7361
Epoch 332/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.7158 - accuracy: 0.7361
Epoch 333/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.6174 - accuracy: 0.7917
Epoch 404/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6162 - accuracy: 0.7917
Epoch 405/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6151 - accuracy: 0.7778
Epoch 406/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.6140 - accuracy: 0.7778
Epoch 407/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6129 - accuracy: 0.7778
Epoch 408/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6117 - accuracy: 0.7917
Epoch 409/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6106 - accuracy: 0.7917
Epoch 410/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6095 - accuracy: 0.7917
Epoch 411/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.6085 - accuracy: 0.7917
Epoch 412/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6076 - accuracy: 0.7778
Epoch 413/1000


Epoch 484/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5465 - accuracy: 0.8750
Epoch 485/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5458 - accuracy: 0.8750
Epoch 486/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5453 - accuracy: 0.8750
Epoch 487/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5445 - accuracy: 0.8750
Epoch 488/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5439 - accuracy: 0.8611
Epoch 489/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.5432 - accuracy: 0.8611
Epoch 490/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.5426 - accuracy: 0.8194
Epoch 491/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5420 - accuracy: 0.7917
Epoch 492/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5414 - accuracy: 0.7917
Epoch 493/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.5409 - accuracy: 0.7917


Epoch 565/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5053 - accuracy: 0.8750
Epoch 566/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5051 - accuracy: 0.8750
Epoch 567/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5045 - accuracy: 0.8750
Epoch 568/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.5042 - accuracy: 0.8750
Epoch 569/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5038 - accuracy: 0.8750
Epoch 570/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5035 - accuracy: 0.8750
Epoch 571/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.5031 - accuracy: 0.8750
Epoch 572/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.5027 - accuracy: 0.8750
Epoch 573/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5023 - accuracy: 0.8750
Epoch 574/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.5019 - accuracy: 0.8750


3/3 [==============================] - 0s 3ms/step - loss: 0.4791 - accuracy: 0.8889
Epoch 646/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.4788 - accuracy: 0.8889
Epoch 647/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4785 - accuracy: 0.8889
Epoch 648/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4783 - accuracy: 0.8889
Epoch 649/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4781 - accuracy: 0.8750
Epoch 650/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4778 - accuracy: 0.8750
Epoch 651/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4776 - accuracy: 0.8750
Epoch 652/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4773 - accuracy: 0.8750
Epoch 653/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4770 - accuracy: 0.8750
Epoch 654/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4768 - accuracy: 0.8750
Epoch 655/1000


3/3 [==============================] - 0s 5ms/step - loss: 0.4539 - accuracy: 0.8750
Epoch 725/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4536 - accuracy: 0.8750
Epoch 726/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.4533 - accuracy: 0.8750
Epoch 727/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4530 - accuracy: 0.8750
Epoch 728/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.8750
Epoch 729/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.4523 - accuracy: 0.8750
Epoch 730/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4519 - accuracy: 0.8750
Epoch 731/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4517 - accuracy: 0.8889
Epoch 732/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.4513 - accuracy: 0.8889
Epoch 733/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4511 - accuracy: 0.8889
Epoch 734/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.4280 - accuracy: 0.8750
Epoch 805/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4278 - accuracy: 0.9028
Epoch 806/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4273 - accuracy: 0.9028
Epoch 807/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4269 - accuracy: 0.9028
Epoch 808/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.9028
Epoch 809/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4261 - accuracy: 0.9028
Epoch 810/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.9028
Epoch 811/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4253 - accuracy: 0.9028
Epoch 812/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.9028
Epoch 813/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.9028
Epoch 814/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.3920 - accuracy: 0.9306
Epoch 886/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3913 - accuracy: 0.9306
Epoch 887/1000
3/3 [==============================] - 0s 9ms/step - loss: 0.3909 - accuracy: 0.9306
Epoch 888/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.3903 - accuracy: 0.9306
Epoch 889/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.3899 - accuracy: 0.9306
Epoch 890/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3893 - accuracy: 0.9306
Epoch 891/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3887 - accuracy: 0.9306
Epoch 892/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3883 - accuracy: 0.9306
Epoch 893/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3878 - accuracy: 0.9306
Epoch 894/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3872 - accuracy: 0.9306
Epoch 895/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.3468 - accuracy: 0.9444
Epoch 967/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3462 - accuracy: 0.9444
Epoch 968/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3453 - accuracy: 0.9444
Epoch 969/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3448 - accuracy: 0.9444
Epoch 970/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3441 - accuracy: 0.9444
Epoch 971/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3436 - accuracy: 0.9444
Epoch 972/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3434 - accuracy: 0.9444
Epoch 973/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3432 - accuracy: 0.9444
Epoch 974/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3427 - accuracy: 0.9583
Epoch 975/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.9583
Epoch 976/1000


In [37]:
modelo3.fit(x_treino, d_treino, epochs=1000)

Epoch 1/1000
3/3 [==============================] - 0s 1ms/step - loss: 1.1426 - accuracy: 0.3056
Epoch 2/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1362 - accuracy: 0.3056
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1308 - accuracy: 0.3056
Epoch 4/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.1251 - accuracy: 0.3056
Epoch 5/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1206 - accuracy: 0.3056
Epoch 6/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.1149 - accuracy: 0.3056
Epoch 7/1000
3/3 [==============================] - 0s 5ms/step - loss: 1.1111 - accuracy: 0.3056
Epoch 8/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.1065 - accuracy: 0.3056
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.1033 - accuracy: 0.3056
Epoch 10/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.0999 - accuracy: 0.3056
Epoch 11/1000
3/3 [

3/3 [==============================] - 0s 2ms/step - loss: 0.9804 - accuracy: 0.7500
Epoch 80/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.9771 - accuracy: 0.7639
Epoch 81/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.9734 - accuracy: 0.7917
Epoch 82/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9701 - accuracy: 0.8056
Epoch 83/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.9670 - accuracy: 0.8333
Epoch 84/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9634 - accuracy: 0.8472
Epoch 85/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9599 - accuracy: 0.8750
Epoch 86/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.9563 - accuracy: 0.8889
Epoch 87/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9531 - accuracy: 0.9306
Epoch 88/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.9500 - accuracy: 0.9167
Epoch 89/1000
3/3 [=====

3/3 [==============================] - 0s 2ms/step - loss: 0.6565 - accuracy: 0.7917
Epoch 161/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.6533 - accuracy: 0.7917
Epoch 162/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6501 - accuracy: 0.7778
Epoch 163/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6471 - accuracy: 0.7639
Epoch 164/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6443 - accuracy: 0.7639
Epoch 165/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6412 - accuracy: 0.7639
Epoch 166/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6382 - accuracy: 0.7639
Epoch 167/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6354 - accuracy: 0.7639
Epoch 168/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.6326 - accuracy: 0.7639
Epoch 169/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.6301 - accuracy: 0.7639
Epoch 170/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.5007 - accuracy: 0.8750
Epoch 242/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4997 - accuracy: 0.8750
Epoch 243/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4984 - accuracy: 0.8750
Epoch 244/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4979 - accuracy: 0.8750
Epoch 245/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4971 - accuracy: 0.8750
Epoch 246/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4960 - accuracy: 0.8750
Epoch 247/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4946 - accuracy: 0.8750
Epoch 248/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4931 - accuracy: 0.8750
Epoch 249/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4920 - accuracy: 0.8750
Epoch 250/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4909 - accuracy: 0.8750
Epoch 251/1000


3/3 [==============================] - 0s 4ms/step - loss: 0.4211 - accuracy: 0.9167
Epoch 323/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4199 - accuracy: 0.9306
Epoch 324/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4189 - accuracy: 0.9306
Epoch 325/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4180 - accuracy: 0.9306
Epoch 326/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4170 - accuracy: 0.9306
Epoch 327/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4161 - accuracy: 0.9306
Epoch 328/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4151 - accuracy: 0.9306
Epoch 329/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4142 - accuracy: 0.9306
Epoch 330/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4133 - accuracy: 0.9306
Epoch 331/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.4125 - accuracy: 0.9306
Epoch 332/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.9444
Epoch 404/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3353 - accuracy: 0.9444
Epoch 405/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3338 - accuracy: 0.9444
Epoch 406/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3340 - accuracy: 0.9444
Epoch 407/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3321 - accuracy: 0.9444
Epoch 408/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3309 - accuracy: 0.9444
Epoch 409/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3299 - accuracy: 0.9444
Epoch 410/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.3282 - accuracy: 0.9444
Epoch 411/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.9444
Epoch 412/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.3260 - accuracy: 0.9444
Epoch 413/1000


3/3 [==============================] - 0s 3ms/step - loss: 0.2460 - accuracy: 0.9722
Epoch 486/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.2450 - accuracy: 0.9583
Epoch 487/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2443 - accuracy: 0.9583
Epoch 488/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2432 - accuracy: 0.9583
Epoch 489/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2421 - accuracy: 0.9583
Epoch 490/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2408 - accuracy: 0.9722
Epoch 491/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2399 - accuracy: 0.9722
Epoch 492/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.2403 - accuracy: 0.9722
Epoch 493/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2389 - accuracy: 0.9722
Epoch 494/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.2368 - accuracy: 0.9722
Epoch 495/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.1756 - accuracy: 0.9861
Epoch 567/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1740 - accuracy: 0.9861
Epoch 568/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1732 - accuracy: 0.9861
Epoch 569/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1725 - accuracy: 0.9861
Epoch 570/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1719 - accuracy: 0.9861
Epoch 571/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1712 - accuracy: 0.9861
Epoch 572/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.1704 - accuracy: 0.9861
Epoch 573/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1697 - accuracy: 0.9861
Epoch 574/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1689 - accuracy: 0.9861
Epoch 575/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.1688 - accuracy: 0.9861
Epoch 576/1000


Epoch 648/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1289 - accuracy: 1.0000
Epoch 649/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.1272 - accuracy: 1.0000
Epoch 650/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1253 - accuracy: 1.0000
Epoch 651/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1249 - accuracy: 0.9861
Epoch 652/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1243 - accuracy: 0.9861
Epoch 653/1000
3/3 [==============================] - ETA: 0s - loss: 0.1291 - accuracy: 0.96 - 0s 3ms/step - loss: 0.1236 - accuracy: 0.9861
Epoch 654/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.1230 - accuracy: 0.9861
Epoch 655/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.1226 - accuracy: 0.9861
Epoch 656/1000
3/3 [==============================] - ETA: 0s - loss: 0.1228 - accuracy: 0.96 - 0s 2ms/step - loss: 0.1223 - accuracy: 0.9861
Epoch 657/1000
3

3/3 [==============================] - 0s 2ms/step - loss: 0.0946 - accuracy: 1.0000
Epoch 729/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0941 - accuracy: 1.0000
Epoch 730/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.0937 - accuracy: 1.0000
Epoch 731/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.0935 - accuracy: 1.0000
Epoch 732/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0935 - accuracy: 0.9861
Epoch 733/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0933 - accuracy: 0.9861
Epoch 734/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0933 - accuracy: 0.9861
Epoch 735/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0931 - accuracy: 0.9861
Epoch 736/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.0927 - accuracy: 0.9861
Epoch 737/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0921 - accuracy: 0.9861
Epoch 738/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.0735 - accuracy: 1.0000
Epoch 810/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0731 - accuracy: 1.0000
Epoch 811/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.0730 - accuracy: 1.0000
Epoch 812/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0730 - accuracy: 1.0000
Epoch 813/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0725 - accuracy: 1.0000
Epoch 814/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0726 - accuracy: 1.0000
Epoch 815/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0720 - accuracy: 1.0000
Epoch 816/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0720 - accuracy: 1.0000
Epoch 817/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0717 - accuracy: 1.0000
Epoch 818/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0714 - accuracy: 1.0000
Epoch 819/1000


3/3 [==============================] - 0s 4ms/step - loss: 0.0588 - accuracy: 1.0000
Epoch 891/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0585 - accuracy: 1.0000
Epoch 892/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0584 - accuracy: 1.0000
Epoch 893/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0583 - accuracy: 1.0000
Epoch 894/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.0581 - accuracy: 1.0000
Epoch 895/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0578 - accuracy: 1.0000
Epoch 896/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0578 - accuracy: 1.0000
Epoch 897/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0577 - accuracy: 1.0000
Epoch 898/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0576 - accuracy: 1.0000
Epoch 899/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.0574 - accuracy: 1.0000
Epoch 900/1000


3/3 [==============================] - 0s 2ms/step - loss: 0.0475 - accuracy: 1.0000
Epoch 973/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0481 - accuracy: 1.0000
Epoch 974/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0485 - accuracy: 1.0000
Epoch 975/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0485 - accuracy: 1.0000
Epoch 976/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0480 - accuracy: 1.0000
Epoch 977/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0474 - accuracy: 1.0000
Epoch 978/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0467 - accuracy: 1.0000
Epoch 979/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0465 - accuracy: 1.0000
Epoch 980/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0467 - accuracy: 1.0000
Epoch 981/1000
3/3 [==============================] - 0s 3ms/step - loss: 0.0471 - accuracy: 1.0000
Epoch 982/1000


In [38]:
loss1, acc1 = modelo1.evaluate(x_teste,  d_teste, verbose=2)
loss2, acc2 = modelo2.evaluate(x_teste,  d_teste, verbose=2)
loss3, acc3 = modelo3.evaluate(x_teste,  d_teste, verbose=2)

1/1 - 0s - loss: 0.3114 - accuracy: 0.9444
1/1 - 0s - loss: 0.4491 - accuracy: 0.8333
1/1 - 0s - loss: 0.0438 - accuracy: 1.0000


In [40]:
print(f"Modelo 1:\nLoss: {loss1}\nAccuracy: {acc1}")
print(f"Modelo 2:\nLoss: {loss2}\nAccuracy: {acc2}")
print(f"Modelo 3:\nLoss: {loss3}\nAccuracy: {acc3}")

Modelo 1:
Loss: 0.3113643527030945
Accuracy: 0.9444444179534912
Modelo 2:
Loss: 0.4490520656108856
Accuracy: 0.8333333134651184
Modelo 3:
Loss: 0.043760135769844055
Accuracy: 1.0
